apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-notebook
  name: my-notebook
  namespace: jupyter
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32386
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: my-notebook
  sessionAffinity: None
  type: NodePort
