apiVersion: v1
kind: Namespace
metadata:
  name: jupyter
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-notebook
  name: my-notebook
  namespace: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-notebook
  strategy: {}
  template:
    metadata:
      labels:
        app: my-notebook
    spec:
      initContainers:
        - image: alpine/git:v2.26.2
          name: git-clone
          args:
            - clone
            - --single-branch
            - --
            - https://github.com/manotasce/data_engineering.git
            - /home/jovyan/work
          securityContext:
            runAsUser: 1
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: git-repo
              mountPath: /home/jovyan/work

      containers:
      - image: k8s.gcr.io/git-sync:v3.0.1
        name: git-sync
        volumeMounts:
            - name: git-repo
              mountPath: /home/jovyan/work
        env:
         - name: GIT_SYNC_REPO
           value: https://github.com/manotasce/data_engineering.git
         - name: GIT_SYNC_DEST
           value: repo  
         - name: GIT_SYNC_BRANCH
           value: master     
      - image: jupyter/scipy-notebook:f1811928b3dd
        name: scipy-notebook
        resources: {}
        command:
            - start-notebook.sh
            - --ip
            - '0.0.0.0'
            - --no-browser
            - --NotebookApp.allow_origin='*'
        ports:
            - containerPort: 8888
        volumeMounts:
            - name: git-repo
              mountPath: /home/jovyan/work
      volumes:
        - name: git-repo
          emptyDir: {}  
status: {}